//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.Data_Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class KingBoardDBEntities1 : DbContext
    {
        public KingBoardDBEntities1()
            : base("name=KingBoardDBEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<InvoiceDetail> InvoiceDetails { get; set; }
        public virtual DbSet<Invoice> Invoices { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<Unit> Units { get; set; }
        public virtual DbSet<User> Users { get; set; }
    
        public virtual int AddCustomer(string customerName, string customerType, string phone)
        {
            var customerNameParameter = customerName != null ?
                new ObjectParameter("CustomerName", customerName) :
                new ObjectParameter("CustomerName", typeof(string));
    
            var customerTypeParameter = customerType != null ?
                new ObjectParameter("CustomerType", customerType) :
                new ObjectParameter("CustomerType", typeof(string));
    
            var phoneParameter = phone != null ?
                new ObjectParameter("Phone", phone) :
                new ObjectParameter("Phone", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AddCustomer", customerNameParameter, customerTypeParameter, phoneParameter);
        }
    
        public virtual int AddInvoiceItem(Nullable<int> invoiceID, Nullable<int> productID, Nullable<decimal> quantity, Nullable<decimal> unitPrice)
        {
            var invoiceIDParameter = invoiceID.HasValue ?
                new ObjectParameter("InvoiceID", invoiceID) :
                new ObjectParameter("InvoiceID", typeof(int));
    
            var productIDParameter = productID.HasValue ?
                new ObjectParameter("ProductID", productID) :
                new ObjectParameter("ProductID", typeof(int));
    
            var quantityParameter = quantity.HasValue ?
                new ObjectParameter("Quantity", quantity) :
                new ObjectParameter("Quantity", typeof(decimal));
    
            var unitPriceParameter = unitPrice.HasValue ?
                new ObjectParameter("UnitPrice", unitPrice) :
                new ObjectParameter("UnitPrice", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AddInvoiceItem", invoiceIDParameter, productIDParameter, quantityParameter, unitPriceParameter);
        }
    
        public virtual int AddProduct(string productName, Nullable<int> unitID, Nullable<decimal> stockQuantity, Nullable<decimal> wholesalePrice, Nullable<decimal> retailPrice, Nullable<decimal> minStockLevel)
        {
            var productNameParameter = productName != null ?
                new ObjectParameter("ProductName", productName) :
                new ObjectParameter("ProductName", typeof(string));
    
            var unitIDParameter = unitID.HasValue ?
                new ObjectParameter("UnitID", unitID) :
                new ObjectParameter("UnitID", typeof(int));
    
            var stockQuantityParameter = stockQuantity.HasValue ?
                new ObjectParameter("StockQuantity", stockQuantity) :
                new ObjectParameter("StockQuantity", typeof(decimal));
    
            var wholesalePriceParameter = wholesalePrice.HasValue ?
                new ObjectParameter("WholesalePrice", wholesalePrice) :
                new ObjectParameter("WholesalePrice", typeof(decimal));
    
            var retailPriceParameter = retailPrice.HasValue ?
                new ObjectParameter("RetailPrice", retailPrice) :
                new ObjectParameter("RetailPrice", typeof(decimal));
    
            var minStockLevelParameter = minStockLevel.HasValue ?
                new ObjectParameter("MinStockLevel", minStockLevel) :
                new ObjectParameter("MinStockLevel", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AddProduct", productNameParameter, unitIDParameter, stockQuantityParameter, wholesalePriceParameter, retailPriceParameter, minStockLevelParameter);
        }
    
        public virtual int AddStock(Nullable<int> productID, Nullable<decimal> quantity)
        {
            var productIDParameter = productID.HasValue ?
                new ObjectParameter("ProductID", productID) :
                new ObjectParameter("ProductID", typeof(int));
    
            var quantityParameter = quantity.HasValue ?
                new ObjectParameter("Quantity", quantity) :
                new ObjectParameter("Quantity", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AddStock", productIDParameter, quantityParameter);
        }
    
        public virtual ObjectResult<Nullable<decimal>> CreateInvoice(string invoiceNumber, Nullable<int> customerID, string invoiceType, Nullable<int> createdBy)
        {
            var invoiceNumberParameter = invoiceNumber != null ?
                new ObjectParameter("InvoiceNumber", invoiceNumber) :
                new ObjectParameter("InvoiceNumber", typeof(string));
    
            var customerIDParameter = customerID.HasValue ?
                new ObjectParameter("CustomerID", customerID) :
                new ObjectParameter("CustomerID", typeof(int));
    
            var invoiceTypeParameter = invoiceType != null ?
                new ObjectParameter("InvoiceType", invoiceType) :
                new ObjectParameter("InvoiceType", typeof(string));
    
            var createdByParameter = createdBy.HasValue ?
                new ObjectParameter("CreatedBy", createdBy) :
                new ObjectParameter("CreatedBy", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<decimal>>("CreateInvoice", invoiceNumberParameter, customerIDParameter, invoiceTypeParameter, createdByParameter);
        }
    
        public virtual ObjectResult<GetAllProducts_Result> GetAllProducts()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetAllProducts_Result>("GetAllProducts");
        }
    
        public virtual int PayInvoice(Nullable<int> invoiceID, Nullable<decimal> amount)
        {
            var invoiceIDParameter = invoiceID.HasValue ?
                new ObjectParameter("InvoiceID", invoiceID) :
                new ObjectParameter("InvoiceID", typeof(int));
    
            var amountParameter = amount.HasValue ?
                new ObjectParameter("Amount", amount) :
                new ObjectParameter("Amount", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PayInvoice", invoiceIDParameter, amountParameter);
        }
    
        public virtual ObjectResult<GetCustomer_Result> GetCustomer(string customerPhone)
        {
            var customerPhoneParameter = customerPhone != null ?
                new ObjectParameter("CustomerPhone", customerPhone) :
                new ObjectParameter("CustomerPhone", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetCustomer_Result>("GetCustomer", customerPhoneParameter);
        }
    
        public virtual ObjectResult<string> GetUnits()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("GetUnits");
        }
    }
}
